# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_mainnav'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainnav',
            table='axf_nav',
        ),
    ]
