# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_mainmustbuy_mainshop'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainshop',
            table='axf_shop',
        ),
    ]
