# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_mainshow'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainshow',
            table='axf_mainshow',
        ),
    ]
