# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='productname',
            field=models.CharField(max_length=200),
        ),
    ]
